[package]
name = "Padloc"
version = "0.1.0"
description = "Padloc"
authors = [ "you" ]
license = ""
repository = "https://github.com/padloc/padloc"
default-run = "Padloc"
edition = "2018"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { version = "1.0.0-beta.8", features = ["api-all"] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
