version: "3"
services:
    padloc:
        build:
            context: .
            args:
                - SERVER_URL=$PL_SERVER_URL
                - CLIENT_URL=$PL_CLIENT_URL
                - STRIPE_PUBLIC_KEY=$PL_STRIPE_PUBLIC_KEY
        ports:
            - $PL_CLIENT_PORT:8080
            - $PL_SERVER_PORT:3000
        environment:
            - PL_EMAIL_USER
            - PL_EMAIL_SERVER
            - PL_EMAIL_PORT
            - PL_EMAIL_PASSWORD
            - PL_EMAIL_FROM
            - PL_REPORT_ERRORS
        volumes:
            - ./data:/data
            - ./docs:/docs
            - ./app:/app
