version: "3.7"
services:
    mongodb:
        image: mongo
        container_name: mongodb
        restart: always
        env_file: .env
        volumes:
            - data:/data/db
        expose:
            - 27017
        # ports:
        #     - 27023:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${PL_DATA_MONGODB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${PL_DATA_MONGODB_PASSWORD}
    server:
        image: padloc/server
        container_name: padloc_server
        build:
            context: .
            dockerfile: Dockerfile-server
        depends_on:
            - mongodb
        env_file: .env
        environment:
            PL_DATA_MONGODB_HOST: mongodb
            PL_DATA_MONGODB_PROTOCOL: mongodb
            PL_DATA_MONGODB_PORT: 27017
            PL_DATA_ATTACHMENTS_BACKEND: fs
            PL_DATA_ATTACHMENTS_DIR: /attachments
        expose:
            - 3000
        volumes:
            - attachments:/attachments
            - logs:/logs
        restart: unless-stopped
    pwa:
        image: padloc/pwa
        container_name: padloc_pwa
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile-pwa
        volumes:
            - pwa:/pwa
        command: ["build"]
        restart: on-failure
    nginx:
        image: nginx
        container_name: nginx
        restart: always
        volumes:
            - pwa:/pwa
            - ./nginx.conf:/etc/nginx/nginx.conf
            # - ${PL_TLS_CERT:-./tls/cert.pem}:/tls/cert
            # - ${PL_TLS_KEY:-./tls/key.pem}:/tls/key
            # - ${PL_TLS_CONF:-./tls/tls.conf}:/tls/tls.conf
        ports:
            - 80:80
            - 443:443
volumes:
    data:
    attachments:
    pwa:
    logs:
