name: Build Web Extension

on:
    workflow_dispatch:
        inputs:
            environment:
                type: choice
                description: "Environment to build for"
                default: "Local"
                required: true
                options:
                    - "Local"
                    - "Beta"
                    - "Production"

    push:
        branches:
            - "v4"
            - "master"
            - "feature/**"
            - "fix/**"
        # TODO: Disabled so it can be tested before making code changes
        # paths:
        #     - "packages/app/**"
        #     - "packages/core/**"
        #     - "packages/extension/**"
        #     - "packages/locale/**"

jobs:
    archive:
        runs-on: ubuntu-latest
        environment: ${{ github.event.inputs.environment || 'Local' }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16.13.1
            - name: Install dependencies
              run: |
                  npm ci
                  npm i -g web-ext@6.6.0
            - name: Build
              run: PL_SERVER_URL=${{ secrets.PL_SERVER_URL }} npm run web-extension:build
            - name: Sign for Firefox
              run: cd packages/extension/dist && web-ext sign --channel=unlisted --api-key=${{ secrets.PL_WEB_EXTENSION_FIREFOX_API_KEY }} --api-secret=${{ secrets.PL_WEB_EXTENSION_FIREFOX_API_SECRET }}
            - name: Archive Signed Web Extension (Firefox)
              uses: actions/upload-artifact@v2
              with:
                  name: signed-web-extension-firefox-${{ github.sha }}
                  path: packages/extension/dist/web-ext-artifacts/*.xpi
                  if-no-files-found: error
            - name: Archive Unsigned Web Extension (Chrome)
              uses: actions/upload-artifact@v2
              with:
                  name: unsigned-web-extension-chrome-${{ github.sha }}
                  path: |
                      packages/extension/dist
                      !web-ext-artifacts
                      !*.xpi
                      !*.zip
                  if-no-files-found: error
